[build]
builder = "nixpacks"

[deploy]
startCommand = "bash -c 'php artisan serve --host=0.0.0.0 --port=${PORT}'"
healthcheckPath = "/"
healthcheckTimeout = 60

[deploy]
preDeployCommand = "bash -c 'php artisan migrate --force && php artisan db:seed --force && php artisan config:clear && php artisan cache:clear && php artisan view:clear && php artisan config:cache && php artisan route:cache'"
